site_name: Pereira DEV Analytics
repo_url: https://github.com/sergioPereiraBR/start_py
repo_name: sergioPereiraBR/start_py
edit_uri: tree/main

watch:
  - .kanbn/...

theme:
  name: material
  language: pt-BR
  logo: assets/logo.png
  favicon: assets/logo.png
  palette:
    - scheme: default
      primary: blue
      toggle:
        icon: material/weather-night
        name: Modo Escuro
    - scheme: slate
      primary: deep blue
      toggle:
        icon: material/weather-sunny
        name: Modo Claro

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.tasklist
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_css:
  - stylesheets/extra.css
  - https://unpkg.com/mermaid@8.5.1/dist/marmaid.css
extra_javascript:
  - https://unpkg.com/mermaid@8.5.1/dist/marmaid.min.js



plugins:
- macros
- search
- autorefs
- mkdocstrings:
    handlers:
      python:
        path: [app]
- coverage:
    page_path: coverage  # default
    html_report_dir: htmlcov  # default

extra:
  grupo:
    variavel: valor
