site_name: Pereira DEV Analytics

theme:
  name: material
  language: pt-BR
  logo: assets/logo.png
  favicon: assets/logo.png


markdown_extensions:
  - attr_list

extra_css:
  - stylesheets/extra.css

plugins:
- mkdocstrings:
    handlers:
      python:
        paths: [app.py]
